spring:
  application:
    name: AvesIas
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:avesbd;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    defer-datasource-initialization: true
    username: admin
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

